### ISSUE TITLE
Question: Fetch to existing api in old-app pages

### ISSUE THREAD

**Issue by terrywarwar** [kentcdodds/incremental-react-router-to-remix-upgrade-path#2]
What happens when the old-app pages make fetch calls to a local api path e.g /api/users.  These go to the fallback route `$.tsx`.  
Do I need another fallback route for `/api/*`?

**Comment by kentcdodds** [comment]
That's what I would do and then that route can have a loader that serves as a proxy to the old API. Or you can put ngnix in front of your app to handle the routing if you want.
